### GET
GET localhost:8080/contas

### GET
GET localhost:8080/contas/1

### POST
POST localhost:8080/contas
Content-Type: application/json

{
  "saldo": 1000.00,
  "ativa": true,
  "clienteId": 1
}

### DELETE
DELETE localhost:8080/contas/1

### GET
GET localhost:8080/contas/1/ativo